#include "stmepic.hpp"
#include "portmacro.h"
/**
 *
 * ################################################################################################################
 *
 *
 * If any of the functions defined here are alrady defined in the CubeMX then delete the one generated by CubeMX
 *
 *
 *
 *
 *
 *
 * ################################################################################################################
 */


#ifdef __cplusplus
extern "C" {
#endif

extern void xPortSysTickHandler(void);


void SysTick_Handler(void) {
  SysTick->CTRL;

  if(xTaskGetSchedulerState() != 1) {
    xPortSysTickHandler();
  }
}

#ifdef __cplusplus
}
#endif