name: clang-format

on: [push]

jobs:
  clang-format:
    runs-on: self-hosted
    container:
      image: xlemonx/arm-gnu-toolchain:13.3.1
      volumes:
        - builds:/builds
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Init environment
        run: git config --global --add safe.directory "*"

      - name: Run clang-format
        run: |
          find src -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format -i

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Apply formating to ${{ github.actor }} commit.' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
